#!/usr/bin/env python3
"""Inject the numbers from metrics/hf.json into README.md.

Everything between the HF-STATS markers is regenerated; the rest of the README
is hand-written and never touched.

    <!-- HF-STATS:START --> ... <!-- HF-STATS:END -->

Usage:
    python3 scripts/render_readme.py [--metrics metrics/hf.json] [--readme README.md]
    python3 scripts/render_readme.py --check   # non-zero exit if out of date
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime
from pathlib import Path

from fetch_hf_stats import comma, human

START = "<!-- HF-STATS:START -->"
END = "<!-- HF-STATS:END -->"


def block(data: dict) -> str:
    display = data["display"]

    try:
        stamp = datetime.strptime(data["updated_at"], "%Y-%m-%dT%H:%M:%SZ").strftime(
            "%d %B %Y"
        )
    except (KeyError, ValueError):
        stamp = data.get("updated_at", "unknown")

    rows = "\n".join(
        f"| [{model['owner']}/{model['name']}]({model['url']}) "
        f"| {model['downloads_display']} | {model['likes']} |"
        for model in data["top_models"]
    )

    # One column per account, so the personal namespace and the OpenMed org -
    # an open-source project with its own contributors - are never summed.
    accounts = data["accounts"]
    per = data["per_account"]

    def row(label: str, key: str, fmt, bold: bool = False) -> str:
        cells = [fmt(per[a][key]) for a in accounts]
        if bold:
            cells = [f"**{c}**" for c in cells]
        return f"| **{label}** | " + " | ".join(cells) + " |"

    header = "| 🤗 Hugging Face | " + " | ".join(
        f"[{a}](https://huggingface.co/{a})" for a in accounts
    ) + " |"
    align = "| --- | " + " | ".join("---:" for _ in accounts) + " |"
    table = "\n".join(
        [
            header,
            align,
            row("Models published", "models", comma),
            row("Datasets published", "datasets", comma),
            row("Downloads, all time", "downloads_all_time", human, bold=True),
            row("Downloads, last 30 days", "downloads_30d", human),
        ]
    )

    return f"""<!-- HF-STATS:START -->
<!-- Generated by scripts/render_readme.py - edit that, not this. -->

{table}

<sub>{display['followers']} followers · {display['likes']} likes received across both · [OpenMed](https://openmed.life/) is an open-source project I created, built in the open with its contributors.</sub>

**Most downloaded, all time**

| Model | Downloads | Likes |
| --- | ---: | ---: |
{rows}

<sub>Live from the <a href="{data['profile_url']}">Hugging Face Hub API</a> · refreshed {stamp}</sub>
<!-- HF-STATS:END -->"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--metrics", default="metrics/hf.json")
    parser.add_argument("--readme", default="README.md")
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify the README is up to date instead of rewriting it",
    )
    args = parser.parse_args()

    data = json.loads(Path(args.metrics).read_text(encoding="utf-8"))
    readme = Path(args.readme)
    text = readme.read_text(encoding="utf-8")

    if START not in text or END not in text:
        print(f"error: {readme} is missing the {START} / {END} markers", file=sys.stderr)
        return 2

    head, _, rest = text.partition(START)
    _, _, tail = rest.partition(END)
    updated = head + block(data) + tail

    if args.check:
        if updated != text:
            print(f"{readme} is out of date - run scripts/render_readme.py", file=sys.stderr)
            return 1
        print(f"{readme} is up to date")
        return 0

    if updated == text:
        print(f"{readme} already current")
        return 0

    readme.write_text(updated, encoding="utf-8")
    print(f"updated {readme}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
