#!/usr/bin/env python3
"""Inject the numbers from metrics/hf.json into README.md.

Everything between the HF-STATS markers is regenerated; the rest of the README
is hand-written and never touched.

    <!-- HF-STATS:START --> ... <!-- HF-STATS:END -->

Usage:
    python3 scripts/render_readme.py [--metrics metrics/hf.json] [--readme README.md]
    python3 scripts/render_readme.py --check   # non-zero exit if out of date
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime
from pathlib import Path

START = "<!-- HF-STATS:START -->"
END = "<!-- HF-STATS:END -->"


def block(data: dict) -> str:
    display = data["display"]

    try:
        stamp = datetime.strptime(data["updated_at"], "%Y-%m-%dT%H:%M:%SZ").strftime(
            "%d %B %Y"
        )
    except (KeyError, ValueError):
        stamp = data.get("updated_at", "unknown")

    rows = "\n".join(
        f"| [{model['owner']}/{model['name']}]({model['url']}) "
        f"| {model['downloads_display']} | {model['likes']} |"
        for model in data["top_models"]
    )

    names = [f"[{a}](https://huggingface.co/{a})" for a in data["accounts"]]
    accounts = " and ".join([", ".join(names[:-1]), names[-1]] if len(names) > 2 else names)

    return f"""<!-- HF-STATS:START -->
<!-- Generated by scripts/render_readme.py - edit that, not this. -->

| 🤗 Hugging Face | |
| --- | --- |
| **Models published** | {display['models']} |
| **Datasets published** | {display['datasets']} |
| **Downloads, all time** | **{display['downloads_all_time']}** |
| **Downloads, last 30 days** | {display['downloads_30d']} |
| **Followers** | {display['followers']} |
| **Likes received** | {display['likes']} |

<sub>Combined across {accounts}, all authored by me.</sub>

**Most downloaded, all time**

| Model | Downloads | Likes |
| --- | ---: | ---: |
{rows}

<sub>Live from the <a href="{data['profile_url']}">Hugging Face Hub API</a> · refreshed {stamp}</sub>
<!-- HF-STATS:END -->"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--metrics", default="metrics/hf.json")
    parser.add_argument("--readme", default="README.md")
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify the README is up to date instead of rewriting it",
    )
    args = parser.parse_args()

    data = json.loads(Path(args.metrics).read_text(encoding="utf-8"))
    readme = Path(args.readme)
    text = readme.read_text(encoding="utf-8")

    if START not in text or END not in text:
        print(f"error: {readme} is missing the {START} / {END} markers", file=sys.stderr)
        return 2

    head, _, rest = text.partition(START)
    _, _, tail = rest.partition(END)
    updated = head + block(data) + tail

    if args.check:
        if updated != text:
            print(f"{readme} is out of date - run scripts/render_readme.py", file=sys.stderr)
            return 1
        print(f"{readme} is up to date")
        return 0

    if updated == text:
        print(f"{readme} already current")
        return 0

    readme.write_text(updated, encoding="utf-8")
    print(f"updated {readme}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
